In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [14]:
# from keras.datasets import mnist

# (x_train, y_train), (x_test, y_test) = mnist.load_data()

# print('X_train: ' + str(x_train.shape))
# print('Y_train: ' + str(y_train.shape))
# print('X_test:  '  + str(x_test.shape))
# print('Y_test:  '  + str(y_test.shape))


In [15]:
# loaded a local file 
data = pd.read_csv('../data/mnist_train.csv')
data.head()

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


In [16]:
data = np.array(data)

In [17]:
m,n = data.shape
np.random.shuffle(data)


In [18]:
data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]

In [19]:
Y_train

array([1, 2, 5, ..., 0, 9, 6], dtype=int64)

In [20]:
X_train[:,0].shape

(784,)

In [24]:
import numpy as np

def init_params():
    W1 = np.random.randn(10,784) - 0.5
    b1 = np.random.randn(10,1) - 0.5
    W2 = np.random.randn(10,10) - 0.5
    b2 = np.random.randn(10,1) - 0.5
    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(0,Z)
    
def softmax(Z):
    return np.exp(Z) / np.sum(np.exp(Z), axis=0)
    
def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2 

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def deriv_ReLU(Z):
    return np.where(Z > 0, 1, 0)

def back_prop(Z1, A1, Z2, A2, W2, X, Y):
    m = Y.size
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2, axis=1, keepdims=True)
    dZ1 = W2.T.dot(dZ2) * deriv_ReLU(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1, axis=1, keepdims=True)
    return dW1, db1, dW2, db2


def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1
    W2 = W2 - alpha * dW2
    b2 = b2 - alpha * db2
    return W1, b1, W2, b2


def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    return np.sum(predictions == Y) / Y.size


def gradient_descent(X, Y, iterations, alpha):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = back_prop(Z1, A1, Z2, A2, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 50 == 0:
            predictions = get_predictions(A2)
            accuracy = get_accuracy(predictions, Y)
            print('Iteration:', i)
            print('Accuracy: ', accuracy)
    return W1, b1, W2, b2


W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 100, 0.1)


Iteration: 0
Accuracy:  0.09927118644067796
Iteration: 50
Accuracy:  0.09927118644067796


In [26]:
def init_params():
    W1 = np.random.rand(10, 784) - 0.5
    b1 = np.random.rand(10, 1) - 0.5
    W2 = np.random.rand(10, 10) - 0.5
    b2 = np.random.rand(10, 1) - 0.5
    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(Z, 0)

def softmax(Z):
    A = np.exp(Z) / sum(np.exp(Z))
    return A
    
def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def ReLU_deriv(Z):
    return Z > 0

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * ReLU_deriv(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)
    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1    
    W2 = W2 - alpha * dW2  
    b2 = b2 - alpha * db2    
    return W1, b1, W2, b2
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 10 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))
    return W1, b1, W2, b2

W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 0.10, 500)

C:\Users\naine\AppData\Local\Temp\ipykernel_7988\80462127.py:12: RuntimeWarning: overflow encountered in exp
  A = np.exp(Z) / sum(np.exp(Z))
C:\Users\naine\AppData\Local\Temp\ipykernel_7988\80462127.py:12: RuntimeWarning: invalid value encountered in divide
  A = np.exp(Z) / sum(np.exp(Z))


Iteration:  0
[9 6 6 ... 6 6 3] [1 2 5 ... 0 9 6]
0.11064406779661017
Iteration:  10
[0 0 0 ... 0 0 0] [1 2 5 ... 0 9 6]
0.09886440677966102
Iteration:  20
[0 0 0 ... 0 0 0] [1 2 5 ... 0 9 6]
0.09886440677966102
Iteration:  30
[0 0 0 ... 0 0 0] [1 2 5 ... 0 9 6]
0.09886440677966102
Iteration:  40
[0 0 0 ... 0 0 0] [1 2 5 ... 0 9 6]
0.09886440677966102
Iteration:  50
[0 0 0 ... 0 0 0] [1 2 5 ... 0 9 6]
0.09886440677966102
Iteration:  60
[0 0 0 ... 0 0 0] [1 2 5 ... 0 9 6]
0.09886440677966102
Iteration:  70
[0 0 0 ... 0 0 0] [1 2 5 ... 0 9 6]
0.09886440677966102
Iteration:  80
[0 0 0 ... 0 0 0] [1 2 5 ... 0 9 6]
0.09886440677966102
Iteration:  90
[0 0 0 ... 0 0 0] [1 2 5 ... 0 9 6]
0.09886440677966102
Iteration:  100
[0 0 0 ... 0 0 0] [1 2 5 ... 0 9 6]
0.09886440677966102
Iteration:  110
[0 0 0 ... 0 0 0] [1 2 5 ... 0 9 6]
0.09886440677966102
Iteration:  120
[0 0 0 ... 0 0 0] [1 2 5 ... 0 9 6]
0.09886440677966102
Iteration:  130
[0 0 0 ... 0 0 0] [1 2 5 ... 0 9 6]
0.09886440677966102
Ite