In [4]:
import numpy as np

In [12]:
x = [1,2,3,4]
print(type(x))
print(x)

<class 'list'>
[1, 2, 3, 4]


In [8]:
l = np.array(x)
type(l)

numpy.ndarray

In [11]:
range1 = np.arange(1,11)
print(rangee)

[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
range2 = np.arange(1,11,2)
range2

array([1, 3, 5, 7, 9])

In [16]:
np.zeros((2,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [73]:
np.random.seed(52)
a = np.random.randint(10,1000,50)
a

array([678, 789, 535, 161,  96, 934, 513, 938, 975, 244, 917, 997, 260,
       173, 493, 875, 749, 811, 271, 251,  26, 149,  64, 440, 308, 711,
       183, 473, 832, 982, 969, 561, 750, 800, 337,  49, 913, 585, 798,
        44, 437, 472, 734, 468, 586, 965, 841,  75, 623,  92])

In [74]:
a.reshape(5,10)

array([[678, 789, 535, 161,  96, 934, 513, 938, 975, 244],
       [917, 997, 260, 173, 493, 875, 749, 811, 271, 251],
       [ 26, 149,  64, 440, 308, 711, 183, 473, 832, 982],
       [969, 561, 750, 800, 337,  49, 913, 585, 798,  44],
       [437, 472, 734, 468, 586, 965, 841,  75, 623,  92]])

In [75]:
a.mean()

538.54

In [71]:
a.argmax()


11

In [76]:
a.shape

(50,)

In [86]:

b = np.ones(10)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])