In [6]:
import tensorflow as tf
#tensorflow has shape and datatype
# int32, float32, string

In [13]:
#creating tensors

string = tf.Variable("this is tensorflow",tf.string)
number = tf.Variable(123,tf.int32)
floating = tf.Variable(3.45,tf.float32)



In [45]:
# ranking/degree of tensors
# this consists off multiple elemensts
tensor1 = tf.Variable([1,2,3,4,5],tf.int32) #rank 1 tenor
tensor2 = tf.Variable(['nainesh','nitin'],tf.string) # rank 1
tensor3 = tf.Variable([[1,2,3],[2,3,4]],tf.int32) #rank 2 , elements should be of similar dimension to be in  a rank2 or 3
tensor4 = tf.Variable([[[5,6,7],[3,4,5],[1,2,3]]],tf.int32) #this is rank 3 tensor
tensor5 = tf.Variable([[[1,2],[3,4],[5,6,]]],tf.int32)

In [46]:
#checking the ranks of the tensors
tf.rank(tensor1), tf.rank(tensor2), tf.rank(tensor3),tf.rank(tensor4), tf.rank(tensor5)

(<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>)

In [48]:
# checking the shape of the tensors
print(tensor1.shape)
print(tensor2.shape)
print(tensor3.shape)
print(tensor4.shape)
print(tensor5.shape)


(5,)
(2,)
(2, 3)
(1, 3, 3)
(1, 3, 2)


In [50]:
# reshaping the tensors
t6 = tf.reshape(tensor5,[2,1,3])

In [52]:
tensor5

<tf.Variable 'Variable:0' shape=(1, 3, 2) dtype=int32, numpy=
array([[[1, 2],
        [3, 4],
        [5, 6]]])>

In [63]:
#create tnensor
t1 = tf.zeros([2,2,2])
print(t1)

tf.Tensor(
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]], shape=(2, 2, 2), dtype=float32)


## **TensorFlow** 


In [4]:
import tensorflow as tf

In [9]:
mnist = tf.keras.datasets.mnist
(x_train,y_train),(x_test,y_test) = mnist.load_data()
x_train,x_test = x_train/255.0,x_test/255.0
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape =(28,28)),
    tf.keras.Dense(128,activation='relu'),
    tf.keras.Dropout(0.2),
    

])